#!/usr/bin/env python3
"""Generate the 1080x1920 cut from the landscape composition.

The vertical cut is the same film, the same timeline and the same real figures —
only the layout is reflowed. Rather than maintain two compositions, this reads
composition/index.html and appends a vertical override stylesheet, so a change to
the landscape edit carries over by re-running this script.

    python3 build-vertical.py
"""
import re
import shutil
from pathlib import Path

SRC = Path("composition")
DST = Path("composition-vertical")

W, H = 1080, 1920
COL = 940                 # content column
CARD_PAD = 40
BAND_TRACK = COL - CARD_PAD * 2          # 860
IV_TRACK = 520
IV_LABEL, IV_GAP, IV_VALUE = 180, 20, 112

# --- band: today against a normal day, from the real NUE row -----------------
B_LO, B_HI = -7.5, 7.5
bx = lambda v: (v - B_LO) / (B_HI - B_LO) * BAND_TRACK
b_zero, b_tlo, b_thi, b_today = bx(0), bx(-2.84), bx(2.84), bx(-6.32)

# --- inversion bars: the real mean returns from public/backtest.json ---------
BUCKETS = {1: -0.142, 2: 0.442, 3: 0.867, 4: 1.073, 5: 2.481}
BASELINE = 0.784
I_LO, I_HI = -0.3, 2.7
ispan = I_HI - I_LO
i_zero = (0 - I_LO) / ispan * IV_TRACK
i_base = IV_LABEL + IV_GAP + i_zero + BASELINE / ispan * IV_TRACK

bars = []
for k, v in BUCKETS.items():
    w = abs(v) / ispan * IV_TRACK
    left = i_zero - w if v < 0 else i_zero
    bars.append(f"      #iv-{k} {{ width: {w:.1f}px; left: {left:.1f}px; }}")

OVERRIDES = f"""
    <style>
      /* ======================================================================
         VERTICAL OVERRIDES — 1080x1920
         Generated by build-vertical.py. Same timeline, same figures, reflowed
         layout. Appended after the base sheet so equal-specificity rules win.

         Type is scaled up, not just reflowed: this canvas is 1080 wide and is
         watched at phone width, so a size that reads fine on a 1920 frame is
         roughly a third smaller in the hand. Nothing readable sits under 22px.
         ====================================================================== */
      .col {{ width: {COL}px; }}
      .eyebrow {{ font-size: 24px; }}
      .headrow .meta {{ font-size: 23px; }}

      /* Scene 1 — narrower grid, so fewer and shorter columns */
      #noise {{ grid-template-columns: repeat(9, 1fr); grid-auto-rows: 34px; padding: 0 18px; }}
      .nc {{ font-size: 14px; gap: 5px; }}
      #s1-scrim {{ height: 420px; }}
      #s1-l1 {{ font-size: 48px; }}
      #s1-l2 {{ font-size: 70px; margin-top: 22px; }}

      /* Scene 2 — the risk block sits under the sectors rather than beside */
      #s2-line {{ font-size: 58px; margin-top: 30px; }}
      #s2-grid {{ grid-template-columns: 1fr; gap: 0; margin-top: 38px; }}
      #s2-risk {{ width: 100%; padding-left: 0; padding-top: 34px; margin-top: 34px;
        border-left: none; border-top: 1px solid var(--rule); }}
      #s2-score {{ font-size: 72px; }}
      #s2-risklabel {{ font-size: 28px; }}
      .srow {{ padding: 18px 0; }}
      .srow .name {{ font-size: 30px; }}
      .bar {{ width: 180px; }}
      .srow .pct {{ width: 130px; font-size: 30px; }}

      /* Scene 3 — mover rows wrap; the multiple gets its own line */
      #s3-line {{ font-size: 58px; margin-top: 28px; }}
      .mrow {{ flex-wrap: wrap; padding: 22px 0; }}
      .mrow .tk {{ width: 80px; font-size: 27px; }}
      .mrow .co {{ width: auto; flex: 1; font-size: 30px; }}
      .mrow .sc {{ display: none; }}
      .mrow .mv {{ width: 160px; font-size: 34px; }}
      .mrow .mx {{ width: 100%; text-align: left; margin-top: 10px; font-size: 24px; }}

      /* Scene 3 — the card */
      .card {{ width: {COL}px; padding: {CARD_PAD}px {CARD_PAD}px {CARD_PAD + 8}px; }}
      .cname {{ font-size: 44px; }}
      .cticker {{ font-size: 25px; }}
      .pct-big {{ font-size: 82px; }}
      .plabel {{ font-size: 24px; }}
      #c-bandtrack, #c-bandlbls {{ width: {BAND_TRACK}px; }}
      #c-bandtrack {{ height: 42px; }}
      #c-typical {{ left: {b_tlo:.1f}px; width: {b_thi - b_tlo:.1f}px; }}
      #c-bandtrack .axis {{ left: {b_zero:.1f}px; }}
      #c-bandtrack .edge.lo {{ left: {b_tlo:.1f}px; }}
      #c-bandtrack .edge.hi {{ left: {b_thi:.1f}px; }}
      #c-todaybar {{ left: {b_today:.1f}px; width: {b_zero - b_today:.1f}px; top: 10px; height: 22px; }}
      #c-bandlbls {{ height: 34px; }}
      #c-bandlbls span {{ font-size: 23px; }}
      /* at this width the two labels collide if both stay under the band,
         so the typical label goes to the track end and today\'s to the start */
      #c-lbl-typ {{ left: auto; right: 0; transform: none; }}
      #c-lbl-today {{ left: 0px; }}
      #c-unusual {{ font-size: 28px; }}
      .figs {{ gap: 0 28px; margin-top: 26px; }}
      .fig dt {{ font-size: 20px; }}
      .fig dd {{ font-size: 40px; }}
      .fnote {{ font-size: 23px; margin-top: 10px; }}
      #c-conc {{ font-size: 44px; margin-top: 38px; }}

      /* Scene 4 — the inversion, on a narrower track */
      #inv {{ width: {IV_LABEL + IV_GAP + IV_TRACK + IV_GAP + IV_VALUE}px; }}
      .ivrow {{ gap: {IV_GAP}px; height: 60px; }}
      .ivrow .lbl {{ width: {IV_LABEL}px; font-size: 24px; }}
      .ivtrack {{ width: {IV_TRACK}px; }}
      .ivval {{ width: {IV_VALUE}px; font-size: 26px; }}
{chr(10).join(bars)}
      #ivbase, #ivbase-lbl {{ left: {i_base:.1f}px; }}
      #ivbase-lbl {{ font-size: 19px; }}
      #s4-sub {{ font-size: 22px; letter-spacing: 0.08em; margin-top: 42px; }}
      #s4-line {{ font-size: 52px; margin-top: 24px; }}

      /* Scene 5 */
      #s5-col {{ width: {COL}px; }}
      #s5-mark {{ font-size: 96px; }}
      #s5-tag {{ font-size: 34px; }}
    </style>
  </head>"""


def main() -> None:
    if DST.exists():
        shutil.rmtree(DST)
    shutil.copytree(SRC, DST, ignore=shutil.ignore_patterns("snapshots", "contact-sheet.jpg"))

    html = (SRC / "index.html").read_text()
    html = html.replace('data-width="1920" data-height="1080"',
                        f'data-width="{W}" data-height="{H}"')
    html = html.replace('content="width=1920, height=1080"', f'content="width={W}, height={H}"')
    html = html.replace('html, body { width: 1920px; height: 1080px;',
                        f'html, body {{ width: {W}px; height: {H}px;')
    assert f'html, body {{ width: {W}px' .replace('{{','{') in html, "base html/body size not rewritten"
    assert f'data-width="{W}"' in html, "canvas size not rewritten"
    html = html.replace("  </head>", OVERRIDES, 1)
    (DST / "index.html").write_text(html)

    meta = DST / "meta.json"
    if meta.exists():
        meta.write_text(re.sub(r'"name"\s*:\s*"[^"]*"', '"name": "composition-vertical"', meta.read_text()))
    print(f"wrote {DST}/index.html  ({W}x{H})")


if __name__ == "__main__":
    main()
