"""Add sentiment aggregates table

Revision ID: 9045cc5fae33
Revises: c804b605a70a
Create Date: 2025-11-22 01:31:59.694452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9045cc5fae33'
down_revision: Union[str, None] = 'c804b605a70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_aggregates',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('bucket', sa.DateTime(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'bucket')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentiment_aggregates')
    # ### end Alembic commands ###
