"""Initial migration

Revision ID: c804b605a70a
Revises: 
Create Date: 2025-11-22 00:44:29.964069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c804b605a70a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_domain', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('is_content_available', sa.Boolean(), nullable=True),
    sa.Column('content_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_url'), 'news_articles', ['url'], unique=True)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('notification_token', sa.Text(), nullable=True),
    sa.Column('notification_preferences', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_ticker_date')
    )
    op.create_index(op.f('ix_daily_prices_date'), 'daily_prices', ['date'], unique=False)
    op.create_index(op.f('ix_daily_prices_id'), 'daily_prices', ['id'], unique=False)
    op.create_index('ix_ticker_date', 'daily_prices', ['ticker', 'date'], unique=False)
    op.create_table('psych_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('emotion', sa.String(length=20), nullable=True),
    sa.Column('hype_velocity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('mention_avg_30d', sa.Integer(), nullable=True),
    sa.Column('top_keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psych_signals_date'), 'psych_signals', ['date'], unique=False)
    op.create_index(op.f('ix_psych_signals_id'), 'psych_signals', ['id'], unique=False)
    op.create_table('quant_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rsi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ma_50', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ma_200', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('signal', sa.String(length=50), nullable=True),
    sa.Column('trend_short', sa.String(length=20), nullable=True),
    sa.Column('trend_long', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quant_signals_date'), 'quant_signals', ['date'], unique=False)
    op.create_index(op.f('ix_quant_signals_id'), 'quant_signals', ['id'], unique=False)
    op.create_table('sentiment_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_events_id'), 'sentiment_events', ['id'], unique=False)
    op.create_index(op.f('ix_sentiment_events_source'), 'sentiment_events', ['source'], unique=False)
    op.create_index(op.f('ix_sentiment_events_source_id'), 'sentiment_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_sentiment_events_ticker'), 'sentiment_events', ['ticker'], unique=False)
    op.create_index(op.f('ix_sentiment_events_timestamp'), 'sentiment_events', ['timestamp'], unique=False)
    op.create_table('sentiment_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('key_factors', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_explanation_ticker_date')
    )
    op.create_index(op.f('ix_sentiment_explanations_date'), 'sentiment_explanations', ['date'], unique=False)
    op.create_index(op.f('ix_sentiment_explanations_id'), 'sentiment_explanations', ['id'], unique=False)
    op.create_index(op.f('ix_sentiment_explanations_ticker'), 'sentiment_explanations', ['ticker'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_id'), 'watchlists', ['id'], unique=False)
    op.create_table('hybrid_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('signal', sa.String(length=20), nullable=False),
    sa.Column('case_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reason_short', sa.String(length=255), nullable=True),
    sa.Column('historical_accuracy', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('avg_gain_when_correct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quant_signal_id', sa.Integer(), nullable=True),
    sa.Column('psych_signal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['psych_signal_id'], ['psych_signals.id'], ),
    sa.ForeignKeyConstraint(['quant_signal_id'], ['quant_signals.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hybrid_signals_confidence'), 'hybrid_signals', ['confidence'], unique=False)
    op.create_index(op.f('ix_hybrid_signals_date'), 'hybrid_signals', ['date'], unique=False)
    op.create_index(op.f('ix_hybrid_signals_id'), 'hybrid_signals', ['id'], unique=False)
    op.create_index(op.f('ix_hybrid_signals_signal'), 'hybrid_signals', ['signal'], unique=False)
    op.create_index(op.f('ix_hybrid_signals_ticker'), 'hybrid_signals', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hybrid_signals_ticker'), table_name='hybrid_signals')
    op.drop_index(op.f('ix_hybrid_signals_signal'), table_name='hybrid_signals')
    op.drop_index(op.f('ix_hybrid_signals_id'), table_name='hybrid_signals')
    op.drop_index(op.f('ix_hybrid_signals_date'), table_name='hybrid_signals')
    op.drop_index(op.f('ix_hybrid_signals_confidence'), table_name='hybrid_signals')
    op.drop_table('hybrid_signals')
    op.drop_index(op.f('ix_watchlists_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_sentiment_explanations_ticker'), table_name='sentiment_explanations')
    op.drop_index(op.f('ix_sentiment_explanations_id'), table_name='sentiment_explanations')
    op.drop_index(op.f('ix_sentiment_explanations_date'), table_name='sentiment_explanations')
    op.drop_table('sentiment_explanations')
    op.drop_index(op.f('ix_sentiment_events_timestamp'), table_name='sentiment_events')
    op.drop_index(op.f('ix_sentiment_events_ticker'), table_name='sentiment_events')
    op.drop_index(op.f('ix_sentiment_events_source_id'), table_name='sentiment_events')
    op.drop_index(op.f('ix_sentiment_events_source'), table_name='sentiment_events')
    op.drop_index(op.f('ix_sentiment_events_id'), table_name='sentiment_events')
    op.drop_table('sentiment_events')
    op.drop_index(op.f('ix_quant_signals_id'), table_name='quant_signals')
    op.drop_index(op.f('ix_quant_signals_date'), table_name='quant_signals')
    op.drop_table('quant_signals')
    op.drop_index(op.f('ix_psych_signals_id'), table_name='psych_signals')
    op.drop_index(op.f('ix_psych_signals_date'), table_name='psych_signals')
    op.drop_table('psych_signals')
    op.drop_index('ix_ticker_date', table_name='daily_prices')
    op.drop_index(op.f('ix_daily_prices_id'), table_name='daily_prices')
    op.drop_index(op.f('ix_daily_prices_date'), table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_news_articles_url'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
